server:
    port: 8080
    servlet:
      context-path: /merchant

spring:
    devtools:
       restart:
         enabled: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://172.20.10.5:3306/merchant?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://localhost:3306/merchant?characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    hikari:
        username: root
        password: Password
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true

    redis:
        #对应第一个数据库
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
