server:
    port: 8080
    servlet:
      context-path: /merchant


spring:
    devtools:
       restart:
         enabled: false
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.25.13.87:3306/merchant?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      url: jdbc:mysql://192.168.1.2:3306/merchant?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: Password
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
    redis:
        #1st database
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
    resources:
      add-mappings: false

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.demo.bean